kind: pipeline
type: docker
name: build-armhf

platform:
  arch: armhf

steps:
 - name: build
   image: node:12
   commands:
     - apt update && apt install -y build-essential git libsecret-1-dev libx11-dev libxkbfile-dev
     - git clone https://github.com/cdr/code-server
     - cd code-server
     - yarn build 1.41.1 .lkgr
     - yarn binary 1.41.1 .lkgr
     - yarn package 1.41.1 .lkgr
     - cp -vRf release ..
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token

 - name: publish
   image: plugins/github-release
   settings:
    api_key:
      from_secret: gh-token
    files: release/*.tar.gz
   when:
    event: tag
