language: node_js
node_js:
  - "12"

env:
  - VSCODE_VERSION="1.36.1" VERSION="lkgr" TARGET="linux"

matrix:
   include:
     - os: osx
       env:
          - VSCODE_VERSION="1.36.1"
     - os: linux
       env:
          - VSCODE_VERSION="1.36.1" TARGET="linux"
     - os: linux
       env:
          - VSCODE_VERSION="1.36.1" TARGET="alpine"
#     - os: windows
#       install:
#          - npm i -g windows-build-tools --vs2017
      
before_script:
  - git clone https://github.com/cdr/code-server -b web --depth=50
  - cd code-server && yarn
  - export VERSION=$TRAVIS_COMMIT
script: 
  - bash scripts/ci.bash

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis CI"
  - git config --local user.email "support@travis-ci.com"
  - export TRAVIS_TAG=LKGR
  - git tag $TRAVIS_TAG -m "CDR-LKGR_$TRAVIS_COMMIT"

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    # DO NOT CHANGE THIS! Travis can replace this since it's a Environment Variable.
    # Head to Settings > Environment variables and set this.
    secure: $GITHUB_API_KEY
  file_glob: true
  file:
    - release/*.tar.gz
    - release/*.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: false

cache:
  yarn: true
  timeout: 1000
  directories:
  - .cache