language: node_js
node_js:
  - "12"

env:
  - VSCODE_VERSION="1.36.1" VERSION="lkgr" TARGET="linux"

matrix:
   include:
    #######################
    #    Linux Matrix     #
    #######################
     - os: linux
       install:
        - sudo apt update && sudo apt install -y libx11-dev libxkbfile-dev libsecret-1-dev realpath
        - type -a realpath
        - git clone https://github.com/cdr/code-server -b web --depth=50
        - cd code-server && yarn
       script:
         - bash scripts/ci.bash
       on_success:
         - ls release/
    #######################
    #    Windows Matrix   #
    #######################
     - os: windows
       install:
        - npm i -g windows-build-tools --vs2017
        - git clone https://github.com/cdr/code-server -b web --depth=50
        - cd code-server && yarn
       script:
         - bash scripts/ci.bash
       on_success:
         - ls build

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    # DO NOT CHANGE THIS! Travis can replace this since it's a Environment Variable.
    # Head to Settings > Environment variables and set this.
    secure: $GITHUB_API_KEY
  file_glob: true
  file:
    - release/*.tar.gz
    - release/*.zip
  skip_cleanup: true
  on:
    tags: true