language: node_js
node_js:
  - "10"

matrix:
   include:
     - os: osx
       env:
          - VSCODE_VERSION="1.41.0" MINIFY="true" PACKAGE="true" VERSION="lkgr"
     - os: linux
       env:
          - VSCODE_VERSION="1.41.0" MINIFY="true" PACKAGE="true" VERSION="lkgr" TARGET="linux"
#     - os: linux
#       dist: xenial
#       arch: arm64
#       env:
          - VSCODE_VERSION="1.41.0" MINIFY="true" PACKAGE="true" VERSION="lkgr" TARGET="raspbian"
     - os: linux
       env:
          - VSCODE_VERSION="1.41.0" MINIFY="true" PACKAGE="true" VERSION="lkgr" TARGET="alpine"
#     - os: windows
#       env:
#          - VSCODE_VERSION="1.41.0"
#       install:
#          - npm i -g windows-build-tools --vs2017
      
before_script:
  - git clone https://github.com/cdr/code-server -b master --depth=50
  - cd code-server && yarn
script: 
  - bash scripts/ci.bash

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis CI"
  - git config --local user.email "support@travis-ci.com"
  - export TRAVIS_TAG=$(echo $VSCODE_VERSION | awk '{print substr($0,1,10);exit}')
  - git tag $TRAVIS_TAG -m "CDR_LKGR_$TRAVIS_TAG"
  - ls $(pwd)

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    # DO NOT CHANGE THIS! Travis can replace this since it's a Environment Variable.
    # Head to Settings > Environment variables and set this.
    secure: $GITHUB_API_KEY
  name: CDR_LKGR_$TRAVIS_TAG
  file_glob: true
  file:
    - release/*.tar.gz
    - release/*.zip
  skip_cleanup: true
  prerelease: true
  overwrite: true
  on:
    tags: false

cache:
  yarn: true
  timeout: 1000
  directories:
    - .cache
